
INSERT INTO posts (user_id, hook, content, type, content_category, status, posted_at, created_at, updated_at, metrics) VALUES
('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Warum ich meinen Job gekündigt habe', 'Vor 6 Monaten habe ich den Schritt gewagt und mein eigenes Unternehmen gegründet. Hier sind meine 3 wichtigsten Learnings...', 'text', 'Personal Story', 'analyzed', now() - interval '88 days', now() - interval '88 days', now() - interval '87 days',
'{"impressions": 320, "likes": 12, "comments": 3, "shares": 1, "engagement_rate": 2.1, "score": 45, "sentiment": "positive", "follower_delta": 5, "ctr": 1.2, "performance_summary": "Guter Einstieg, persönliche Stories kommen an.", "what_worked": ["Authentischer Ton", "Klarer Hook"], "what_to_improve": ["Mehr CTA einbauen"], "recommended_follow_ups": ["Follow-up zu Gründungs-Learnings"], "topic_tags": ["Entrepreneurship", "Personal Brand"], "content_pattern": "storytelling"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', '3 Tools die jeder Gründer kennen sollte', 'Produktivität ist alles. Diese 3 Tools haben meine Arbeitsweise komplett verändert...', 'text', 'Industry Insights', 'analyzed', now() - interval '82 days', now() - interval '82 days', now() - interval '81 days',
'{"impressions": 410, "likes": 18, "comments": 5, "shares": 3, "engagement_rate": 2.8, "score": 52, "sentiment": "positive", "follower_delta": 8, "ctr": 1.5, "performance_summary": "Listicle-Format funktioniert gut bei der Zielgruppe.", "what_worked": ["Konkrete Empfehlungen", "Listicle-Format"], "what_to_improve": ["Screenshots hinzufügen"], "recommended_follow_ups": ["Deep-dive zu jedem Tool"], "topic_tags": ["Productivity", "Tools"], "content_pattern": "listicle"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Der größte Fehler im B2B-Vertrieb', 'Ich habe 50 Cold Calls gemacht und dabei einen entscheidenden Fehler immer wiederholt...', 'text', 'Case Study', 'analyzed', now() - interval '74 days', now() - interval '74 days', now() - interval '73 days',
'{"impressions": 520, "likes": 22, "comments": 8, "shares": 4, "engagement_rate": 3.1, "score": 58, "sentiment": "neutral", "follower_delta": 11, "ctr": 1.8, "performance_summary": "Fehler-Posts erzeugen hohe Resonanz.", "what_worked": ["Verletzlichkeit zeigen", "Konkretes Beispiel"], "what_to_improve": ["Lösung stärker betonen"], "recommended_follow_ups": ["Cold Call Script teilen"], "topic_tags": ["Sales", "B2B"], "content_pattern": "lesson_learned"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'LinkedIn ist kein Lebenslauf', 'Hör auf, deinen Feed wie einen Lebenslauf zu behandeln. Hier ist, was stattdessen funktioniert...', 'carousel', 'Leadership', 'analyzed', now() - interval '68 days', now() - interval '68 days', now() - interval '67 days',
'{"impressions": 680, "likes": 35, "comments": 12, "shares": 7, "engagement_rate": 3.5, "score": 65, "sentiment": "positive", "follower_delta": 18, "ctr": 2.1, "performance_summary": "Carousel mit kontroverser These hat sehr gut performt.", "what_worked": ["Kontroverse These", "Carousel-Format"], "what_to_improve": ["Mehr Slides nutzen"], "recommended_follow_ups": ["Content-Strategie für LinkedIn"], "topic_tags": ["LinkedIn", "Content Strategy"], "content_pattern": "contrarian"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Mein Morning Routine als CEO', 'Um 5:30 klingelt der Wecker. Nicht weil ich muss, sondern weil ich will. Hier ist mein System...', 'text', 'Personal Story', 'analyzed', now() - interval '58 days', now() - interval '58 days', now() - interval '57 days',
'{"impressions": 750, "likes": 38, "comments": 14, "shares": 5, "engagement_rate": 3.2, "score": 62, "sentiment": "positive", "follower_delta": 15, "ctr": 1.9, "performance_summary": "Routine-Posts haben treue Leserschaft.", "what_worked": ["Persönlicher Einblick", "Strukturierter Ablauf"], "what_to_improve": ["Weniger Hustle-Culture-Vibes"], "recommended_follow_ups": ["Evening Routine teilen"], "topic_tags": ["Productivity", "Leadership"], "content_pattern": "routine"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Warum ich keine Investoren suche', 'Bootstrapping ist nicht sexy. Aber es gibt dir etwas, das kein VC der Welt kaufen kann: Freiheit.', 'text', 'Leadership', 'analyzed', now() - interval '52 days', now() - interval '52 days', now() - interval '51 days',
'{"impressions": 890, "likes": 45, "comments": 18, "shares": 9, "engagement_rate": 3.8, "score": 70, "sentiment": "positive", "follower_delta": 22, "ctr": 2.3, "performance_summary": "Starke Meinung + persönliche Erfahrung = hohe Engagement-Rate.", "what_worked": ["Klare Positionierung", "Emotionaler Trigger"], "what_to_improve": ["Zahlen/Daten einbauen"], "recommended_follow_ups": ["Bootstrapping-Zahlen teilen"], "topic_tags": ["Bootstrapping", "Startup"], "content_pattern": "opinion"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', '10.000€ MRR in 6 Monaten', 'Hier ist der genaue Weg, wie wir von 0 auf 10K MRR gekommen sind. Kein Bullshit, nur Fakten.', 'carousel', 'Case Study', 'analyzed', now() - interval '44 days', now() - interval '44 days', now() - interval '43 days',
'{"impressions": 1250, "likes": 62, "comments": 24, "shares": 15, "engagement_rate": 4.2, "score": 78, "sentiment": "positive", "follower_delta": 35, "ctr": 2.8, "performance_summary": "Transparente Zahlen generieren massiv Engagement und Shares.", "what_worked": ["Transparenz mit Zahlen", "Carousel mit Daten"], "what_to_improve": ["Mehr Kontext zu Rückschlägen"], "recommended_follow_ups": ["Kosten-Breakdown teilen"], "topic_tags": ["Revenue", "Startup Growth"], "content_pattern": "case_study"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Was ich von 100 Kundengesprächen gelernt habe', 'Nach 100 Discovery Calls habe ich 5 Muster erkannt, die jedes Mal auftauchen...', 'text', 'Industry Insights', 'analyzed', now() - interval '40 days', now() - interval '40 days', now() - interval '39 days',
'{"impressions": 980, "likes": 48, "comments": 16, "shares": 8, "engagement_rate": 3.6, "score": 68, "sentiment": "positive", "follower_delta": 20, "ctr": 2.0, "performance_summary": "Datenbasierte Learnings kommen gut an.", "what_worked": ["Konkrete Zahl im Hook", "Pattern-Erkennung"], "what_to_improve": ["Beispiele pro Pattern"], "recommended_follow_ups": ["Interview-Leitfaden teilen"], "topic_tags": ["Customer Discovery", "B2B"], "content_pattern": "data_insight"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Hört auf Perfektion zu jagen', 'Der beste Zeitpunkt zu starten war gestern. Der zweitbeste ist jetzt. Hier ist warum...', 'text', 'Leadership', 'analyzed', now() - interval '36 days', now() - interval '36 days', now() - interval '35 days',
'{"impressions": 1100, "likes": 55, "comments": 20, "shares": 11, "engagement_rate": 3.9, "score": 72, "sentiment": "positive", "follower_delta": 25, "ctr": 2.2, "performance_summary": "Motivations-Content performt solide, aber nicht top.", "what_worked": ["Universelle Message", "Starker erster Satz"], "what_to_improve": ["Mehr eigene Erfahrung einbauen"], "recommended_follow_ups": ["Eigene Perfektionismus-Story"], "topic_tags": ["Mindset", "Entrepreneurship"], "content_pattern": "motivational"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'So habe ich meinen ersten Mitarbeiter eingestellt', 'Vom Solo-Founder zum Team. Die Entscheidung, die alles verändert hat...', 'text', 'Personal Story', 'analyzed', now() - interval '28 days', now() - interval '28 days', now() - interval '27 days',
'{"impressions": 1350, "likes": 68, "comments": 28, "shares": 14, "engagement_rate": 4.5, "score": 80, "sentiment": "positive", "follower_delta": 32, "ctr": 2.6, "performance_summary": "Meilenstein-Posts erzeugen hohe emotionale Resonanz.", "what_worked": ["Persönlicher Meilenstein", "Emotionale Tiefe"], "what_to_improve": ["Hiring-Prozess detaillierter"], "recommended_follow_ups": ["Hiring-Checkliste teilen"], "topic_tags": ["Hiring", "Team Building"], "content_pattern": "milestone"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Die Wahrheit über Work-Life-Balance', 'Es gibt keine Balance. Es gibt nur bewusste Entscheidungen. Hier sind meine 4 Regeln...', 'carousel', 'Leadership', 'analyzed', now() - interval '24 days', now() - interval '24 days', now() - interval '23 days',
'{"impressions": 1480, "likes": 72, "comments": 30, "shares": 16, "engagement_rate": 4.3, "score": 82, "sentiment": "neutral", "follower_delta": 28, "ctr": 2.5, "performance_summary": "Kontroverses Thema mit hohem Engagement.", "what_worked": ["Kontroverse Perspektive", "Klare Regeln"], "what_to_improve": ["Mehr Nuancen zeigen"], "recommended_follow_ups": ["Tagesablauf als Gründer"], "topic_tags": ["Work-Life", "Leadership"], "content_pattern": "contrarian"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Mein Tech-Stack für unter 100€/Monat', 'Du brauchst kein großes Budget für große Ergebnisse. Hier ist unser kompletter Stack...', 'carousel', 'Industry Insights', 'analyzed', now() - interval '21 days', now() - interval '21 days', now() - interval '20 days',
'{"impressions": 1620, "likes": 78, "comments": 25, "shares": 20, "engagement_rate": 4.1, "score": 76, "sentiment": "positive", "follower_delta": 30, "ctr": 2.7, "performance_summary": "Praxisnahe Tool-Posts werden stark gesaved und geshared.", "what_worked": ["Konkreter Nutzen", "Budget-Framing"], "what_to_improve": ["Alternativen nennen"], "recommended_follow_ups": ["Automations-Stack zeigen"], "topic_tags": ["Tools", "Bootstrapping"], "content_pattern": "listicle"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Ich habe 30 Tage nur auf LinkedIn gepostet', '30 Tage, 30 Posts. Hier sind die Ergebnisse und was ich nie wieder machen werde...', 'carousel', 'Case Study', 'analyzed', now() - interval '14 days', now() - interval '14 days', now() - interval '13 days',
'{"impressions": 1850, "likes": 92, "comments": 38, "shares": 22, "engagement_rate": 4.8, "score": 85, "sentiment": "positive", "follower_delta": 42, "ctr": 3.1, "performance_summary": "Meta-Content über LinkedIn performt hervorragend auf LinkedIn.", "what_worked": ["Meta-Thema", "Datenbasiert", "30-Tage-Challenge-Format"], "what_to_improve": ["Mehr visuelle Daten"], "recommended_follow_ups": ["Best Practices aus der Challenge"], "topic_tags": ["LinkedIn", "Content Strategy", "Experiment"], "content_pattern": "experiment"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Der eine Satz der alles verändert hat', 'Ein Mentor sagte mir: Du baust kein Produkt. Du löst ein Problem. Das hat alles verändert.', 'text', 'Personal Story', 'analyzed', now() - interval '10 days', now() - interval '10 days', now() - interval '9 days',
'{"impressions": 1720, "likes": 85, "comments": 32, "shares": 18, "engagement_rate": 4.5, "score": 83, "sentiment": "positive", "follower_delta": 38, "ctr": 2.9, "performance_summary": "Kurze, prägnante Stories mit Aha-Moment performen top.", "what_worked": ["Kurz und prägnant", "Aha-Moment", "Mentor-Zitat"], "what_to_improve": ["Mehr Kontext zum Wandel"], "recommended_follow_ups": ["Weitere Mentor-Learnings"], "topic_tags": ["Mentorship", "Mindset"], "content_pattern": "storytelling"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'So gewinnst du deine ersten 10 Kunden', 'Vergiss Ads. Vergiss Funnels. Hier ist der simpelste Weg zu deinen ersten zahlenden Kunden...', 'carousel', 'Case Study', 'analyzed', now() - interval '7 days', now() - interval '7 days', now() - interval '6 days',
'{"impressions": 1950, "likes": 95, "comments": 35, "shares": 24, "engagement_rate": 4.6, "score": 86, "sentiment": "positive", "follower_delta": 40, "ctr": 3.0, "performance_summary": "Actionable How-To mit kontraintuitivem Ansatz = Viral-Potenzial.", "what_worked": ["Kontraintuitiver Einstieg", "Step-by-Step", "Für Anfänger zugänglich"], "what_to_improve": ["Eigene Ergebnisse zeigen"], "recommended_follow_ups": ["Kunden-Retention Strategien"], "topic_tags": ["Customer Acquisition", "Startup"], "content_pattern": "how_to"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Mein größter Fehler als Gründer 2024', 'Ich habe 3 Monate an einem Feature gebaut, das niemand wollte. So stelle ich sicher, dass das nie wieder passiert...', 'text', 'Personal Story', 'analyzed', now() - interval '4 days', now() - interval '4 days', now() - interval '3 days',
'{"impressions": 2100, "likes": 102, "comments": 42, "shares": 26, "engagement_rate": 5.0, "score": 88, "sentiment": "positive", "follower_delta": 45, "ctr": 3.2, "performance_summary": "Verletzlichkeit + konkretes Learning = bester Post bisher.", "what_worked": ["Radikale Ehrlichkeit", "Konkrete Zeitangabe", "Lösung mitgeliefert"], "what_to_improve": ["Noch mehr Detail zum Entscheidungsprozess"], "recommended_follow_ups": ["Feature-Validation Framework teilen"], "topic_tags": ["Product Development", "Failure"], "content_pattern": "lesson_learned"}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', 'Warum ich aufgehört habe Bücher zu lesen', 'Unpopular Opinion: Bücher lesen ist der langsamste Weg zu lernen. Hier ist was ich stattdessen mache...', 'text', 'Leadership', 'draft', now() - interval '1 day', now() - interval '1 day', now(),
'{}'),

('e46243c2-c7b5-4bfb-94a6-3e1789ba6bcf', '5 Automations die mir 10h pro Woche sparen', 'Zeit ist die einzige Ressource die du nicht skalieren kannst. Außer du automatisierst richtig...', 'carousel', 'Industry Insights', 'draft', now(), now(), now(),
'{}');
