// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyxwfsqpwiochtrzugol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eHdmc3Fwd2lvY2h0cnp1Z29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTcyMDcsImV4cCI6MjA4OTA3MzIwN30.qMlJYpTyHbauAx3scpztTO1r4UH4KM0IOSABoMEayZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});